# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ricar/Desktop/EletronicaConfiguravel/ConfigurableEletronic/ClassPL3 - Lab3-20200305/Lab3_sources/project_1/project_1.srcs/sources_1/ip/sine_mid/sine_mid.xci
# IP: The module: 'sine_mid' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ricar/Desktop/EletronicaConfiguravel/ConfigurableEletronic/ClassPL3 - Lab3-20200305/Lab3_sources/project_1/project_1.srcs/sources_1/ip/sine_mid/sine_mid_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sine_mid'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ricar/Desktop/EletronicaConfiguravel/ConfigurableEletronic/ClassPL3 - Lab3-20200305/Lab3_sources/project_1/project_1.srcs/sources_1/ip/sine_mid/sine_mid.xci
# IP: The module: 'sine_mid' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ricar/Desktop/EletronicaConfiguravel/ConfigurableEletronic/ClassPL3 - Lab3-20200305/Lab3_sources/project_1/project_1.srcs/sources_1/ip/sine_mid/sine_mid_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sine_mid'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
