# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/modulator_ipi_rtl.xdc

# Block Designs: bd/modulator_ipi/modulator_ipi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi || ORIG_REF_NAME==modulator_ipi} -quiet] -quiet

# IP: bd/modulator_ipi/ip/modulator_ipi_pwm_0_0/modulator_ipi_pwm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_pwm_0_0 || ORIG_REF_NAME==modulator_ipi_pwm_0_0} -quiet] -quiet

# IP: bd/modulator_ipi/ip/modulator_ipi_counter_0_0/modulator_ipi_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_counter_0_0 || ORIG_REF_NAME==modulator_ipi_counter_0_0} -quiet] -quiet

# IP: bd/modulator_ipi/ip/modulator_ipi_sine_0_0/modulator_ipi_sine_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_sine_0_0 || ORIG_REF_NAME==modulator_ipi_sine_0_0} -quiet] -quiet

# IP: bd/modulator_ipi/ip/modulator_ipi_xlconstant_0_0/modulator_ipi_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_xlconstant_0_0 || ORIG_REF_NAME==modulator_ipi_xlconstant_0_0} -quiet] -quiet

# IP: bd/modulator_ipi/ip/modulator_ipi_xlconstant_0_1/modulator_ipi_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_xlconstant_0_1 || ORIG_REF_NAME==modulator_ipi_xlconstant_0_1} -quiet] -quiet

# IP: bd/modulator_ipi/ip/modulator_ipi_xlconstant_0_2/modulator_ipi_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_xlconstant_0_2 || ORIG_REF_NAME==modulator_ipi_xlconstant_0_2} -quiet] -quiet

# IP: bd/modulator_ipi/ip/modulator_ipi_xlconstant_0_3/modulator_ipi_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_xlconstant_0_3 || ORIG_REF_NAME==modulator_ipi_xlconstant_0_3} -quiet] -quiet

# IP: bd/modulator_ipi/ip/modulator_ipi_frequency_trigger_0_0_1/modulator_ipi_frequency_trigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_frequency_trigger_0_0 || ORIG_REF_NAME==modulator_ipi_frequency_trigger_0_0} -quiet] -quiet

# XDC: bd/modulator_ipi/modulator_ipi_ooc.xdc
